services:
  db:
    image: mariadb:10.6
    container_name: greenwear-db
    restart: always
    environment:
      MARIADB_DATABASE: greenwear_db
      MARIADB_USER: greenwear_user
      MARIADB_PASSWORD: greenwear_password
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend-spring/demo
    container_name: greenwear-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/greenwear_db
      - SPRING_DATASOURCE_USERNAME=greenwear_user
      - SPRING_DATASOURCE_PASSWORD=greenwear_password
      - APP_JWT_SECRET=your-super-strong-jwt-secret-key-for-dev
    ports:
      - "8081:8080" # 로컬 8081 -> 컨테이너 8080

  frontend:
    build:
      context: ./frontend
    container_name: greenwear-frontend
    restart: always
    ports:
      - "8080:80" # 로컬 8080 -> 컨테이너 80 (Nginx)
    depends_on:
      - backend

volumes:
  db-data:
