services:
  # Spring Boot Backend (Docker)
  - type: web
    name: greenwear-backend-spring
    runtime: docker
    dockerfilePath: ./backend-spring/demo/Dockerfile
    dockerContext: ./backend-spring/demo
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:testdb
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.h2.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.H2Dialect
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "true"
    healthCheckPath: /api/health
    
  # Vue.js Frontend
  - type: web
    name: greenwear-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npx serve -s dist -l 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://greenwear-backend-spring.onrender.com
    
  # Node.js Backend (Alternative)
  - type: web
    name: greenwear-backend-node
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        value: mongodb+srv://demo:demo@cluster0.mongodb.net/greenwear
    healthCheckPath: /api/health

databases:
  # PostgreSQL for production
  - name: greenwear-db
    databaseName: greenwear
    user: greenwear_user 