server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  profiles:
    active: railway-simple
    
  # Use H2 in-memory database for Railway deployment
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  h2:
    console:
      enabled: true
      path: /h2-console

# Disable all management endpoints to avoid conflicts
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
  metrics:
    enabled: false

logging:
  level:
    com.greenwear: INFO
    org.springframework.boot: INFO
    root: INFO
    org.springframework.context: INFO
    org.springframework.beans: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.boot.web.embedded.tomcat: INFO
    org.springframework.boot.actuate: INFO
    org.springframework.web.servlet: INFO
    org.springframework.boot.web.server: INFO