spring:
  application:
    name: greenwear-demo
  
  # Database Configuration (MariaDB)
  datasource:
    url: jdbc:mariadb://localhost:3306/greenwear_db
    username: greenwear_user
    password: greenwear_password
    driver-class-name: org.mariadb.jdbc.Driver
  
  # H2 Console (for debugging)
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
app:
  jwt:
    secret: greenWearSecretKey2024ForJWTTokenGeneration
    expiration: 86400000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.greenwear: DEBUG
    org.springframework.security: DEBUG 