server:
  port: ${PORT:8080}
  
spring:
  profiles:
    active: fly
    
  datasource:
    url: jdbc:h2:file:/data/greenwear;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000  # 1 year
        
  mvc:
    view:
      prefix: classpath:/static/
      suffix: .html

jwt:
  secret: ${JWT_SECRET:myFlySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000

logging:
  level:
    com.greenwear: INFO
    org.springframework.web: WARN
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true 