server:
  port: ${PORT:8080}
  
spring:
  profiles:
    active: railway
    
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  web:
    resources:
      static-locations: classpath:/static/
      
  mvc:
    view:
      prefix: classpath:/static/
      suffix: .html

jwt:
  secret: ${JWT_SECRET:myRailwaySecretKey12345678901234567890123456789012345678901234567890}
  expiration: 86400000

logging:
  level:
    com.greenwear: INFO
    org.springframework.web: WARN
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 