spring:
  application:
    name: greenwear-demo
  
  # Database Configuration (PostgreSQL for production, H2 for local)
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:greenwear_db}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  
  # H2 Console (for debugging - only in local)
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
    defer-datasource-initialization: true
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: ${PORT:8080}

# JWT Configuration
app:
  jwt:
    secret: greenWearSecretKey2024ForJWTTokenGeneration
    expiration: 86400000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.greenwear: DEBUG
    org.springframework.security: DEBUG 