server:
  port: ${PORT:8080}

spring:
  profiles:
    active: heroku
    
  # Use H2 in-memory database
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# Disable all management features
management:
  endpoints:
    enabled-by-default: false
  metrics:
    enabled: false

# Minimal logging
logging:
  level:
    root: WARN
    com.greenwear: INFO
