spring:
  # Database Configuration for Production (PostgreSQL)
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: false
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    defer-datasource-initialization: true

# Server Configuration
server:
  port: ${PORT:8080}

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:greenWearSecretKey2024ForJWTTokenGeneration}
    expiration: 86400000

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    com.greenwear: INFO
    org.springframework.security: WARN
    org.hibernate: WARN