# ===================== 공통 =====================
server:
  port: ${PORT:8080}

spring:
  application:
    name: blog-promotion-generator

logging:
  level:
    com.bloggen: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# ===================== 개발용(H2) =====================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false

# ===================== 운영용(PostgreSQL on Railway) =====================
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${PGHOST:${DB_HOST}}:${PGPORT:${DB_PORT}}/${PGDATABASE:${DB_NAME}}
    username: ${PGUSER:${DB_USER}}
    password: ${PGPASSWORD:${DB_PASS}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 처음엔 update 권장(스키마 확인 후 필요시 none)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  jackson:
    serialization:
      write-dates-as-timestamps: false 